image: alpine

stages:
  - build

variables:
  ALPINE_BASE_PACKAGES: 'g++ ninja cmake'
  ALPINE_APPLICATION_PACKAGES: 'mesa-gl glew-dev sdl2-dev'

gcc-debug:
  stage: build
  before_script:
    - apk add --no-cache $ALPINE_BASE_PACKAGES $ALPINE_APPLICATION_PACKAGES
  script:
    - mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Debug -GNinja && ninja

gcc-release:
  stage: build
  before_script:
    - apk add --no-cache $ALPINE_BASE_PACKAGES $ALPINE_APPLICATION_PACKAGES
  script:
    - mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -GNinja && ninja

clang-release:
  stage: build
  before_script:
    - apk add --no-cache $ALPINE_BASE_PACKAGES $ALPINE_APPLICATION_PACKAGES clang clang-dev
  script:
    - export CC=/usr/bin/clang
    - export CXX=/usr/bin/clang++
    - mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -GNinja && ninja
